"""
backfill_hero_alt.py — derive alt text for every blog hero image (Daniel directive 2026-08-07).

REUSE-FIRST: the R2 pool filenames ARE content descriptions (e.g.
cinematic_wide_shot_of_a_minimalist_balinese_infinity_pool_merging_with_the).
This script turns them into clean Title Case alt text with no generation.

Inputs (JSON dumps from D1, produced via wrangler d1 execute --json):
  /tmp/hero_images.json  -> [{ id, filename }]
  /tmp/posts.json        -> [{ id, slug, hero_image }]
Output: /tmp/backfill_alt.sql (UPDATE statements for hero_images.alt_text +
posts.hero_alt) — applied with wrangler d1 execute --remote --file, then
read-back verified.

The derivation rules here MUST mirror deriveHeroAlt() in
repos/blog-agent/src/index.ts (the pipeline writes the same style of alt).

Usage: python backfill_hero_alt.py [hero_images.json] [posts.json] [out.sql]
Defaults: C:/Users/daniel/AppData/Local/Temp/hero_images.json, posts.json, backfill_alt.sql
"""

import json
import re
import sys

# Camera/style prefixes — stripped from the start of the filename (longest
# first so e.g. close_up_detail_of_a_ wins over close_up_of_a_).
PREFIXES = [
    "cinematic_wide_shot_of_",
    "close_up_architectural_detail_of_a_",
    "architectural_detail_of_a_",
    "architectural_shot_of_a_",
    "close_up_detail_of_a_",
    "extreme_close_up_of_a_",
    "interior_detail_of_a_",
    "long_distance_shot_of_a_",
    "mid_range_shot_of_an_",
    "minimalist_brand_image_a_",
    "outdoor_dining_area_at_",
    "panoramic_view_of_an_",
    "panoramic_view_of_a_",
    "pov_looking_down_into_a_",
    "pov_looking_up_through_the_",
    "pov_looking_up_at_a_",
    "pov_looking_down_a_",
    "pov_walking_through_a_",
    "pov_shot_walking_through_a_",
    "pov_sitting_at_a_",
    "pov_detail_of_a_",
    "top_down_macro_shot_of_",
    "top_down_shot_of_a_",
    "ultra_wide_low_angle_shot_of_a_",
    "vertical_architectural_shot_of_a_",
    "vertical_pov_shot_walking_through_a_",
    "vertical_shot_of_a_",
    "wide_interior_shot_of_a_",
    "wide_shot_of_a_",
    "close_up_of_a_",
    "interior_of_an_",
    "interior_of_a_",
    "detail_shot_of_a_",
    "detail_of_a_",
    "macro_shot_of_",
    "view_from_a_",
    "top_down_macro_shot_of_",
    "top_down_shot_of_a_",
    "a_",
]
# Sort longest first for anchor matching.
PREFIXES = sorted(PREFIXES, key=len, reverse=True)

# Non-pool files with fixed alt text (brand assets).
SPECIAL = {
    "og-alpha-default": "Alpha Digital Agency Brand Banner",
    "screen": "Alpha Digital Agency Website Screenshot",
    "website_direct_booking_alpha": "Alpha Digital Agency Website with Direct Booking",
    "direct_booking_slide2": "Alpha Digital Agency Direct Booking Slide 2",
    "direct_booking_slide3": "Alpha Digital Agency Direct Booking Slide 3",
    "direct_booking_slide4": "Alpha Digital Agency Direct Booking Slide 4",
}

TRAILING_ARTICLES = {"the", "with", "of", "a", "an"}


def derive_alt(filename_or_path: str) -> str:
    """Turn a hero filename/path into human-readable alt text."""
    name = filename_or_path.rsplit("/", 1)[-1]  # basename
    stem = re.sub(r"\.(png|jpe?g|webp)$", "", name, flags=re.I)
    if stem in SPECIAL:
        return SPECIAL[stem]
    # Drop duplicate-suffix markers like _1
    stem = re.sub(r"_\d+$", "", stem)
    for prefix in PREFIXES:
        if stem.startswith(prefix):
            stem = stem[len(prefix):]
            break
    words = [w for w in stem.replace("_", " ").split() if w]
    # Drop leading articles and camera-junk tokens ("a point of view pov shot walking..." -> "walking...")
    while words and words[0].lower() in {"a", "an", "the", "of", "point", "pov", "portrait", "style", "shot", "view"}:
        words.pop(0)
    # Strip trailing article fragments ("...merging with the" -> "...merging")
    while words and words[-1].lower() in TRAILING_ARTICLES:
        words.pop()
    if not words:
        return ""
    # Sentence case — reads naturally as alt text ("Balinese brass temple bell...")
    return " ".join([words[0].capitalize()] + [w.lower() for w in words[1:]])


def main() -> None:
    import os
    tmp = os.environ.get("TEMP", "C:/Users/daniel/AppData/Local/Temp")
    hero_path = sys.argv[1] if len(sys.argv) > 1 else f"{tmp}/hero_images.json"
    posts_path = sys.argv[2] if len(sys.argv) > 2 else f"{tmp}/posts.json"
    out_path = sys.argv[3] if len(sys.argv) > 3 else f"{tmp}/backfill_alt.sql"

    with open(hero_path, encoding="utf-8") as f:
        hero_data = json.load(f)
    with open(posts_path, encoding="utf-8") as f:
        post_data = json.load(f)

    heroes = hero_data[0]["results"]
    posts = post_data[0]["results"]

    lines = [
        "-- Auto-generated by repos/blog/tools/backfill_hero_alt.py (2026-08-07)",
        "-- Daniel directive: every blog image carries a description (alt).",
        "-- Derived from R2 pool filenames — REUSE-FIRST, no generation.",
        "",
    ]
    hero_updates = 0
    post_updates = 0
    empty_alts = []

    for h in heroes:
        alt = derive_alt(h["filename"])
        if not alt:
            empty_alts.append(f"hero_images id={h['id']} ({h['filename']})")
            continue
        esc = alt.replace("'", "''")
        lines.append(
            f"UPDATE hero_images SET alt_text = '{esc}' WHERE id = {h['id']} AND "
            f"(alt_text IS NULL OR alt_text = '');"
        )
        hero_updates += 1

    for p in posts:
        alt = derive_alt(p["hero_image"])
        if not alt:
            empty_alts.append(f"posts id={p['id']} ({p['slug']})")
            continue
        esc = alt.replace("'", "''")
        lines.append(
            f"UPDATE posts SET hero_alt = '{esc}' WHERE id = {p['id']} AND "
            f"(hero_alt IS NULL OR hero_alt = '');"
        )
        post_updates += 1

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"hero_images alt_text: {hero_updates}/{len(heroes)} rows")
    print(f"posts hero_alt: {post_updates}/{len(posts)} rows")
    print(f"SQL written: {out_path}")
    if empty_alts:
        print(f"EMPTY ALTS ({len(empty_alts)}):")
        for e in empty_alts:
            print(f"  {e}")
    # Sample preview
    print("\nSamples:")
    for h in heroes[:4]:
        print(f"  {h['filename']} -> {derive_alt(h['filename'])}")
    for p in posts[:2]:
        print(f"  {p['hero_image']} -> {derive_alt(p['hero_image'])}")


if __name__ == "__main__":
    sys.exit(main())
